// Generated by gencpp from file xMo/JointState.msg
// DO NOT EDIT!


#ifndef XMO_MESSAGE_JOINTSTATE_H
#define XMO_MESSAGE_JOINTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xMo
{
template <class ContainerAllocator>
struct JointState_
{
  typedef JointState_<ContainerAllocator> Type;

  JointState_()
    : kp()
    , kd()
    , q()
    , qd()
    , tau()  {
    }
  JointState_(const ContainerAllocator& _alloc)
    : kp(_alloc)
    , kd(_alloc)
    , q(_alloc)
    , qd(_alloc)
    , tau(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kp_type;
  _kp_type kp;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _kd_type;
  _kd_type kd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _q_type;
  _q_type q;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _qd_type;
  _qd_type qd;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _tau_type;
  _tau_type tau;





  typedef boost::shared_ptr< ::xMo::JointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xMo::JointState_<ContainerAllocator> const> ConstPtr;

}; // struct JointState_

typedef ::xMo::JointState_<std::allocator<void> > JointState;

typedef boost::shared_ptr< ::xMo::JointState > JointStatePtr;
typedef boost::shared_ptr< ::xMo::JointState const> JointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xMo::JointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xMo::JointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xMo::JointState_<ContainerAllocator1> & lhs, const ::xMo::JointState_<ContainerAllocator2> & rhs)
{
  return lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd &&
    lhs.q == rhs.q &&
    lhs.qd == rhs.qd &&
    lhs.tau == rhs.tau;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xMo::JointState_<ContainerAllocator1> & lhs, const ::xMo::JointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xMo

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xMo::JointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xMo::JointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xMo::JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xMo::JointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xMo::JointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xMo::JointState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xMo::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f7290d5674702cd40cbe0d31ba4f2cd";
  }

  static const char* value(const ::xMo::JointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f7290d5674702cdULL;
  static const uint64_t static_value2 = 0x40cbe0d31ba4f2cdULL;
};

template<class ContainerAllocator>
struct DataType< ::xMo::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xMo/JointState";
  }

  static const char* value(const ::xMo::JointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xMo::JointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] kp\n"
"float32[] kd\n"
"float32[] q\n"
"float32[] qd\n"
"float32[] tau\n"
;
  }

  static const char* value(const ::xMo::JointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xMo::JointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kp);
      stream.next(m.kd);
      stream.next(m.q);
      stream.next(m.qd);
      stream.next(m.tau);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xMo::JointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xMo::JointState_<ContainerAllocator>& v)
  {
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd[i]);
    }
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "qd[]" << std::endl;
    for (size_t i = 0; i < v.qd.size(); ++i)
    {
      s << indent << "  qd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.qd[i]);
    }
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tau[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XMO_MESSAGE_JOINTSTATE_H
