// Generated by gencpp from file xterra/JointData.msg
// DO NOT EDIT!


#ifndef XTERRA_MESSAGE_JOINTDATA_H
#define XTERRA_MESSAGE_JOINTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xterra
{
template <class ContainerAllocator>
struct JointData_
{
  typedef JointData_<ContainerAllocator> Type;

  JointData_()
    : q()
    , dq()
    , tau()
    , kp()
    , kd()  {
      q.assign(0.0);

      dq.assign(0.0);

      tau.assign(0.0);

      kp.assign(0.0);

      kd.assign(0.0);
  }
  JointData_(const ContainerAllocator& _alloc)
    : q()
    , dq()
    , tau()
    , kp()
    , kd()  {
  (void)_alloc;
      q.assign(0.0);

      dq.assign(0.0);

      tau.assign(0.0);

      kp.assign(0.0);

      kd.assign(0.0);
  }



   typedef boost::array<float, 12>  _q_type;
  _q_type q;

   typedef boost::array<float, 12>  _dq_type;
  _dq_type dq;

   typedef boost::array<float, 12>  _tau_type;
  _tau_type tau;

   typedef boost::array<float, 12>  _kp_type;
  _kp_type kp;

   typedef boost::array<float, 12>  _kd_type;
  _kd_type kd;





  typedef boost::shared_ptr< ::xterra::JointData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xterra::JointData_<ContainerAllocator> const> ConstPtr;

}; // struct JointData_

typedef ::xterra::JointData_<std::allocator<void> > JointData;

typedef boost::shared_ptr< ::xterra::JointData > JointDataPtr;
typedef boost::shared_ptr< ::xterra::JointData const> JointDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xterra::JointData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xterra::JointData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xterra::JointData_<ContainerAllocator1> & lhs, const ::xterra::JointData_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q &&
    lhs.dq == rhs.dq &&
    lhs.tau == rhs.tau &&
    lhs.kp == rhs.kp &&
    lhs.kd == rhs.kd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xterra::JointData_<ContainerAllocator1> & lhs, const ::xterra::JointData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xterra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xterra::JointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xterra::JointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::JointData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::JointData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::JointData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::JointData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xterra::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4cd50c73c6116c031f40dbf7442d3e43";
  }

  static const char* value(const ::xterra::JointData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4cd50c73c6116c03ULL;
  static const uint64_t static_value2 = 0x1f40dbf7442d3e43ULL;
};

template<class ContainerAllocator>
struct DataType< ::xterra::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xterra/JointData";
  }

  static const char* value(const ::xterra::JointData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xterra::JointData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[12] q\n"
"float32[12] dq\n"
"float32[12] tau\n"
"float32[12] kp\n"
"float32[12] kd\n"
;
  }

  static const char* value(const ::xterra::JointData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xterra::JointData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
      stream.next(m.dq);
      stream.next(m.tau);
      stream.next(m.kp);
      stream.next(m.kd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xterra::JointData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xterra::JointData_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "dq[]" << std::endl;
    for (size_t i = 0; i < v.dq.size(); ++i)
    {
      s << indent << "  dq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dq[i]);
    }
    s << indent << "tau[]" << std::endl;
    for (size_t i = 0; i < v.tau.size(); ++i)
    {
      s << indent << "  tau[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tau[i]);
    }
    s << indent << "kp[]" << std::endl;
    for (size_t i = 0; i < v.kp.size(); ++i)
    {
      s << indent << "  kp[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kp[i]);
    }
    s << indent << "kd[]" << std::endl;
    for (size_t i = 0; i < v.kd.size(); ++i)
    {
      s << indent << "  kd[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.kd[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XTERRA_MESSAGE_JOINTDATA_H
