// Generated by gencpp from file xterra/QuadLog.msg
// DO NOT EDIT!


#ifndef XTERRA_MESSAGE_QUADLOG_H
#define XTERRA_MESSAGE_QUADLOG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <xterra/Point.h>
#include <xterra/Quaternion.h>
#include <xterra/Point.h>
#include <xterra/Point.h>
#include <xterra/Point.h>
#include <xterra/Point.h>
#include <xterra/Point.h>
#include <xterra/Point.h>

namespace xterra
{
template <class ContainerAllocator>
struct QuadLog_
{
  typedef QuadLog_<ContainerAllocator> Type;

  QuadLog_()
    : contact_state()
    , contact_prob()
    , contact_force()
    , base_position()
    , base_orientation()
    , linear_velocity()
    , angular_velocity()
    , base_wrench()
    , joint_position()
    , joint_velocity()
    , joint_torque()
    , foot_FL_position()
    , foot_FR_position()
    , foot_RL_position()
    , foot_RR_position()  {
      contact_state.assign(0.0);

      contact_prob.assign(0.0);

      contact_force.assign(0.0);

      base_wrench.assign(0.0);

      joint_position.assign(0.0);

      joint_velocity.assign(0.0);

      joint_torque.assign(0.0);
  }
  QuadLog_(const ContainerAllocator& _alloc)
    : contact_state()
    , contact_prob()
    , contact_force()
    , base_position(_alloc)
    , base_orientation(_alloc)
    , linear_velocity(_alloc)
    , angular_velocity(_alloc)
    , base_wrench()
    , joint_position()
    , joint_velocity()
    , joint_torque()
    , foot_FL_position(_alloc)
    , foot_FR_position(_alloc)
    , foot_RL_position(_alloc)
    , foot_RR_position(_alloc)  {
  (void)_alloc;
      contact_state.assign(0.0);

      contact_prob.assign(0.0);

      contact_force.assign(0.0);

      base_wrench.assign(0.0);

      joint_position.assign(0.0);

      joint_velocity.assign(0.0);

      joint_torque.assign(0.0);
  }



   typedef boost::array<float, 4>  _contact_state_type;
  _contact_state_type contact_state;

   typedef boost::array<float, 4>  _contact_prob_type;
  _contact_prob_type contact_prob;

   typedef boost::array<float, 12>  _contact_force_type;
  _contact_force_type contact_force;

   typedef  ::xterra::Point_<ContainerAllocator>  _base_position_type;
  _base_position_type base_position;

   typedef  ::xterra::Quaternion_<ContainerAllocator>  _base_orientation_type;
  _base_orientation_type base_orientation;

   typedef  ::xterra::Point_<ContainerAllocator>  _linear_velocity_type;
  _linear_velocity_type linear_velocity;

   typedef  ::xterra::Point_<ContainerAllocator>  _angular_velocity_type;
  _angular_velocity_type angular_velocity;

   typedef boost::array<float, 6>  _base_wrench_type;
  _base_wrench_type base_wrench;

   typedef boost::array<float, 12>  _joint_position_type;
  _joint_position_type joint_position;

   typedef boost::array<float, 12>  _joint_velocity_type;
  _joint_velocity_type joint_velocity;

   typedef boost::array<float, 12>  _joint_torque_type;
  _joint_torque_type joint_torque;

   typedef  ::xterra::Point_<ContainerAllocator>  _foot_FL_position_type;
  _foot_FL_position_type foot_FL_position;

   typedef  ::xterra::Point_<ContainerAllocator>  _foot_FR_position_type;
  _foot_FR_position_type foot_FR_position;

   typedef  ::xterra::Point_<ContainerAllocator>  _foot_RL_position_type;
  _foot_RL_position_type foot_RL_position;

   typedef  ::xterra::Point_<ContainerAllocator>  _foot_RR_position_type;
  _foot_RR_position_type foot_RR_position;





  typedef boost::shared_ptr< ::xterra::QuadLog_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xterra::QuadLog_<ContainerAllocator> const> ConstPtr;

}; // struct QuadLog_

typedef ::xterra::QuadLog_<std::allocator<void> > QuadLog;

typedef boost::shared_ptr< ::xterra::QuadLog > QuadLogPtr;
typedef boost::shared_ptr< ::xterra::QuadLog const> QuadLogConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xterra::QuadLog_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xterra::QuadLog_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xterra::QuadLog_<ContainerAllocator1> & lhs, const ::xterra::QuadLog_<ContainerAllocator2> & rhs)
{
  return lhs.contact_state == rhs.contact_state &&
    lhs.contact_prob == rhs.contact_prob &&
    lhs.contact_force == rhs.contact_force &&
    lhs.base_position == rhs.base_position &&
    lhs.base_orientation == rhs.base_orientation &&
    lhs.linear_velocity == rhs.linear_velocity &&
    lhs.angular_velocity == rhs.angular_velocity &&
    lhs.base_wrench == rhs.base_wrench &&
    lhs.joint_position == rhs.joint_position &&
    lhs.joint_velocity == rhs.joint_velocity &&
    lhs.joint_torque == rhs.joint_torque &&
    lhs.foot_FL_position == rhs.foot_FL_position &&
    lhs.foot_FR_position == rhs.foot_FR_position &&
    lhs.foot_RL_position == rhs.foot_RL_position &&
    lhs.foot_RR_position == rhs.foot_RR_position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xterra::QuadLog_<ContainerAllocator1> & lhs, const ::xterra::QuadLog_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xterra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xterra::QuadLog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xterra::QuadLog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::QuadLog_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::QuadLog_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::QuadLog_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::QuadLog_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xterra::QuadLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "97219c6e55d563574e753c5fd3dfae5a";
  }

  static const char* value(const ::xterra::QuadLog_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x97219c6e55d56357ULL;
  static const uint64_t static_value2 = 0x4e753c5fd3dfae5aULL;
};

template<class ContainerAllocator>
struct DataType< ::xterra::QuadLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xterra/QuadLog";
  }

  static const char* value(const ::xterra::QuadLog_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xterra::QuadLog_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] contact_state\n"
"float32[4] contact_prob\n"
"float32[12] contact_force\n"
"Point base_position\n"
"Quaternion base_orientation\n"
"Point linear_velocity\n"
"Point angular_velocity\n"
"float32[6] base_wrench\n"
"float32[12] joint_position\n"
"float32[12] joint_velocity\n"
"float32[12] joint_torque\n"
"Point foot_FL_position\n"
"Point foot_FR_position\n"
"Point foot_RL_position\n"
"Point foot_RR_position\n"
"\n"
"================================================================================\n"
"MSG: xterra/Point\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"\n"
"================================================================================\n"
"MSG: xterra/Quaternion\n"
"float32 x\n"
"float32 y\n"
"float32 z\n"
"float32 w\n"
;
  }

  static const char* value(const ::xterra::QuadLog_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xterra::QuadLog_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.contact_state);
      stream.next(m.contact_prob);
      stream.next(m.contact_force);
      stream.next(m.base_position);
      stream.next(m.base_orientation);
      stream.next(m.linear_velocity);
      stream.next(m.angular_velocity);
      stream.next(m.base_wrench);
      stream.next(m.joint_position);
      stream.next(m.joint_velocity);
      stream.next(m.joint_torque);
      stream.next(m.foot_FL_position);
      stream.next(m.foot_FR_position);
      stream.next(m.foot_RL_position);
      stream.next(m.foot_RR_position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuadLog_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xterra::QuadLog_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xterra::QuadLog_<ContainerAllocator>& v)
  {
    s << indent << "contact_state[]" << std::endl;
    for (size_t i = 0; i < v.contact_state.size(); ++i)
    {
      s << indent << "  contact_state[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.contact_state[i]);
    }
    s << indent << "contact_prob[]" << std::endl;
    for (size_t i = 0; i < v.contact_prob.size(); ++i)
    {
      s << indent << "  contact_prob[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.contact_prob[i]);
    }
    s << indent << "contact_force[]" << std::endl;
    for (size_t i = 0; i < v.contact_force.size(); ++i)
    {
      s << indent << "  contact_force[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.contact_force[i]);
    }
    s << indent << "base_position: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.base_position);
    s << indent << "base_orientation: ";
    s << std::endl;
    Printer< ::xterra::Quaternion_<ContainerAllocator> >::stream(s, indent + "  ", v.base_orientation);
    s << indent << "linear_velocity: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.linear_velocity);
    s << indent << "angular_velocity: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.angular_velocity);
    s << indent << "base_wrench[]" << std::endl;
    for (size_t i = 0; i < v.base_wrench.size(); ++i)
    {
      s << indent << "  base_wrench[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.base_wrench[i]);
    }
    s << indent << "joint_position[]" << std::endl;
    for (size_t i = 0; i < v.joint_position.size(); ++i)
    {
      s << indent << "  joint_position[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_position[i]);
    }
    s << indent << "joint_velocity[]" << std::endl;
    for (size_t i = 0; i < v.joint_velocity.size(); ++i)
    {
      s << indent << "  joint_velocity[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_velocity[i]);
    }
    s << indent << "joint_torque[]" << std::endl;
    for (size_t i = 0; i < v.joint_torque.size(); ++i)
    {
      s << indent << "  joint_torque[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_torque[i]);
    }
    s << indent << "foot_FL_position: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_FL_position);
    s << indent << "foot_FR_position: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_FR_position);
    s << indent << "foot_RL_position: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_RL_position);
    s << indent << "foot_RR_position: ";
    s << std::endl;
    Printer< ::xterra::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.foot_RR_position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XTERRA_MESSAGE_QUADLOG_H
