// Generated by gencpp from file xterra/SensorData.msg
// DO NOT EDIT!


#ifndef XTERRA_MESSAGE_SENSORDATA_H
#define XTERRA_MESSAGE_SENSORDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xterra
{
template <class ContainerAllocator>
struct SensorData_
{
  typedef SensorData_<ContainerAllocator> Type;

  SensorData_()
    : q()
    , dq()
    , ddq()
    , tau_est()
    , quat()
    , gyro()
    , accel()
    , rpy()  {
      q.assign(0.0);

      dq.assign(0.0);

      ddq.assign(0.0);

      tau_est.assign(0.0);

      quat.assign(0.0);

      gyro.assign(0.0);

      accel.assign(0.0);

      rpy.assign(0.0);
  }
  SensorData_(const ContainerAllocator& _alloc)
    : q()
    , dq()
    , ddq()
    , tau_est()
    , quat()
    , gyro()
    , accel()
    , rpy()  {
  (void)_alloc;
      q.assign(0.0);

      dq.assign(0.0);

      ddq.assign(0.0);

      tau_est.assign(0.0);

      quat.assign(0.0);

      gyro.assign(0.0);

      accel.assign(0.0);

      rpy.assign(0.0);
  }



   typedef boost::array<float, 12>  _q_type;
  _q_type q;

   typedef boost::array<float, 12>  _dq_type;
  _dq_type dq;

   typedef boost::array<float, 12>  _ddq_type;
  _ddq_type ddq;

   typedef boost::array<float, 12>  _tau_est_type;
  _tau_est_type tau_est;

   typedef boost::array<float, 4>  _quat_type;
  _quat_type quat;

   typedef boost::array<float, 3>  _gyro_type;
  _gyro_type gyro;

   typedef boost::array<float, 3>  _accel_type;
  _accel_type accel;

   typedef boost::array<float, 3>  _rpy_type;
  _rpy_type rpy;





  typedef boost::shared_ptr< ::xterra::SensorData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xterra::SensorData_<ContainerAllocator> const> ConstPtr;

}; // struct SensorData_

typedef ::xterra::SensorData_<std::allocator<void> > SensorData;

typedef boost::shared_ptr< ::xterra::SensorData > SensorDataPtr;
typedef boost::shared_ptr< ::xterra::SensorData const> SensorDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xterra::SensorData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xterra::SensorData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xterra::SensorData_<ContainerAllocator1> & lhs, const ::xterra::SensorData_<ContainerAllocator2> & rhs)
{
  return lhs.q == rhs.q &&
    lhs.dq == rhs.dq &&
    lhs.ddq == rhs.ddq &&
    lhs.tau_est == rhs.tau_est &&
    lhs.quat == rhs.quat &&
    lhs.gyro == rhs.gyro &&
    lhs.accel == rhs.accel &&
    lhs.rpy == rhs.rpy;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xterra::SensorData_<ContainerAllocator1> & lhs, const ::xterra::SensorData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace xterra

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xterra::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xterra::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::SensorData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::SensorData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::SensorData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::SensorData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xterra::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6caa27b62e69714cfa5e8eacb4ded76";
  }

  static const char* value(const ::xterra::SensorData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6caa27b62e69714ULL;
  static const uint64_t static_value2 = 0xcfa5e8eacb4ded76ULL;
};

template<class ContainerAllocator>
struct DataType< ::xterra::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xterra/SensorData";
  }

  static const char* value(const ::xterra::SensorData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xterra::SensorData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[12] q\n"
"float32[12] dq\n"
"float32[12] ddq\n"
"float32[12] tau_est\n"
"float32[4] quat\n"
"float32[3] gyro\n"
"float32[3] accel\n"
"float32[3] rpy\n"
;
  }

  static const char* value(const ::xterra::SensorData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xterra::SensorData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.q);
      stream.next(m.dq);
      stream.next(m.ddq);
      stream.next(m.tau_est);
      stream.next(m.quat);
      stream.next(m.gyro);
      stream.next(m.accel);
      stream.next(m.rpy);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SensorData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xterra::SensorData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::xterra::SensorData_<ContainerAllocator>& v)
  {
    s << indent << "q[]" << std::endl;
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      s << indent << "  q[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.q[i]);
    }
    s << indent << "dq[]" << std::endl;
    for (size_t i = 0; i < v.dq.size(); ++i)
    {
      s << indent << "  dq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.dq[i]);
    }
    s << indent << "ddq[]" << std::endl;
    for (size_t i = 0; i < v.ddq.size(); ++i)
    {
      s << indent << "  ddq[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.ddq[i]);
    }
    s << indent << "tau_est[]" << std::endl;
    for (size_t i = 0; i < v.tau_est.size(); ++i)
    {
      s << indent << "  tau_est[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.tau_est[i]);
    }
    s << indent << "quat[]" << std::endl;
    for (size_t i = 0; i < v.quat.size(); ++i)
    {
      s << indent << "  quat[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.quat[i]);
    }
    s << indent << "gyro[]" << std::endl;
    for (size_t i = 0; i < v.gyro.size(); ++i)
    {
      s << indent << "  gyro[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.gyro[i]);
    }
    s << indent << "accel[]" << std::endl;
    for (size_t i = 0; i < v.accel.size(); ++i)
    {
      s << indent << "  accel[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.accel[i]);
    }
    s << indent << "rpy[]" << std::endl;
    for (size_t i = 0; i < v.rpy.size(); ++i)
    {
      s << indent << "  rpy[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rpy[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // XTERRA_MESSAGE_SENSORDATA_H
