// Generated by gencpp from file xterra/Point.msg
// DO NOT EDIT!

#ifndef XTERRA_MESSAGE_POINT_H
#define XTERRA_MESSAGE_POINT_H

#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

namespace xterra
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : x(0.0), y(0.0), z(0.0), phi(0.0), psi(0.0), theta(0.0) {
  }

  Point_(const ContainerAllocator& _alloc)
    : x(0.0), y(0.0), z(0.0), phi(0.0), psi(0.0), theta(0.0) {
    (void)_alloc;
  }

  typedef float _x_type;
  _x_type x;

  typedef float _y_type;
  _y_type y;

  typedef float _z_type;
  _z_type z;

  typedef float _phi_type;
  _phi_type phi;

  typedef float _psi_type;
  _psi_type psi;

  typedef float _theta_type;
  _theta_type theta;

  typedef boost::shared_ptr< ::xterra::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xterra::Point_<ContainerAllocator> const> ConstPtr;
}; // struct Point_

typedef ::xterra::Point_<std::allocator<void>> Point;
typedef boost::shared_ptr< ::xterra::Point > PointPtr;
typedef boost::shared_ptr< ::xterra::Point const> PointConstPtr;

// operator==
template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::xterra::Point_<ContainerAllocator1>& lhs, const ::xterra::Point_<ContainerAllocator2>& rhs)
{
  return lhs.x == rhs.x &&
         lhs.y == rhs.y &&
         lhs.z == rhs.z &&
         lhs.phi == rhs.phi &&
         lhs.psi == rhs.psi &&
         lhs.theta == rhs.theta;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::xterra::Point_<ContainerAllocator1>& lhs, const ::xterra::Point_<ContainerAllocator2>& rhs)
{
  return !(lhs == rhs);
}

} // namespace xterra

namespace ros
{
namespace message_traits
{

template <class ContainerAllocator>
struct IsMessage< ::xterra::Point_<ContainerAllocator> > : TrueType { };

template <class ContainerAllocator>
struct IsMessage< ::xterra::Point_<ContainerAllocator> const> : TrueType { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::Point_<ContainerAllocator> > : TrueType { };

template <class ContainerAllocator>
struct IsFixedSize< ::xterra::Point_<ContainerAllocator> const> : TrueType { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::Point_<ContainerAllocator> > : FalseType { };

template <class ContainerAllocator>
struct HasHeader< ::xterra::Point_<ContainerAllocator> const> : FalseType { };

template<class ContainerAllocator>
struct MD5Sum< ::xterra::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a2f27b6883d77b9bdb24a9db1bfc83f6"; // New MD5 after adding 3 fields
  }

  static const char* value(const ::xterra::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa2f27b6883d77b9bULL;
  static const uint64_t static_value2 = 0xdb24a9db1bfc83f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::xterra::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xterra/Point";
  }

  static const char* value(const ::xterra::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xterra::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
           "float32 y\n"
           "float32 z\n"
           "float32 phi\n"
           "float32 psi\n"
           "float32 theta\n";
  }

  static const char* value(const ::xterra::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator>
  struct Serializer< ::xterra::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T>
    inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
      stream.next(m.phi);
      stream.next(m.psi);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xterra::Point_<ContainerAllocator> >
{
  template<typename Stream>
  static void stream(Stream& s, const std::string& indent, const ::xterra::Point_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
    s << indent << "phi: ";
    Printer<float>::stream(s, indent + "  ", v.phi);
    s << indent << "psi: ";
    Printer<float>::stream(s, indent + "  ", v.psi);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // XTERRA_MESSAGE_POINT_H
