module xterra {
    module msg {
        module dds_ {
            struct CliData_ {
                float x[6];
                double duration;
                long mode;
            };
        };
    };
};


