module xterra {
    module msg {
        module dds_ {
            struct IndicatorData_ {
                boolean led1;
                boolean led2;
                boolean led3;
                boolean buzzer;
            };
        };
    };
};