module xterra {
    module msg {
        module dds_ {
            struct SensorData_ {
                float q[6];
                float dq[6];
                float tau[6];
            };
        };
    };
};